// <auto-generated />
using System;
using GeziRotasi.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GeziRotasi.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250827110415_AddSpecialDayHoursTable")]
    partial class AddSpecialDayHoursTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GeziRotasi.API.Models.Poi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("ExternalApiId")
                        .HasColumnType("text");

                    b.Property<string>("GirisUcreti")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("OpeningHours")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int?>("OrtalamaZiyaretSuresi")
                        .HasColumnType("integer");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Website")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.ToTable("Pois");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Müze",
                            Description = "Osmanlı İmparatorluğu'nun...",
                            Latitude = 41.011600000000001,
                            Longitude = 28.9834,
                            Name = "Topkapı Sarayı"
                        },
                        new
                        {
                            Id = 2,
                            Category = "Alışveriş",
                            Description = "Dünyanın en eski ve en büyük...",
                            Latitude = 41.0107,
                            Longitude = 28.9681,
                            Name = "Kapalıçarşı"
                        },
                        new
                        {
                            Id = 3,
                            Category = "Tarihi_Yapı",
                            Description = "Mavi Camii olarak da bilinir...",
                            Latitude = 41.005400000000002,
                            Longitude = 28.976800000000001,
                            Name = "Sultanahmet Camii"
                        },
                        new
                        {
                            Id = 4,
                            Category = "Müze",
                            Description = "Tarihi yarımadanın kalbinde...",
                            Latitude = 41.008600000000001,
                            Longitude = 28.98,
                            Name = "Ayasofya Tarih ve Deneyim Müzesi"
                        },
                        new
                        {
                            Id = 5,
                            Category = "Müze",
                            Description = "Büyüleyici atmosferi ile...",
                            Latitude = 41.008400000000002,
                            Longitude = 28.977900000000002,
                            Name = "Yerebatan Sarnıcı"
                        });
                });

            modelBuilder.Entity("GeziRotasi.API.Models.SpecialDayHour", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<TimeOnly?>("CloseTime")
                        .HasColumnType("time without time zone");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<string>("Description")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<TimeOnly?>("OpenTime")
                        .HasColumnType("time without time zone");

                    b.Property<int>("PoiId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PoiId");

                    b.ToTable("SpecialDayHours");
                });

            modelBuilder.Entity("GeziRotasi.API.Models.WorkingHour", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<TimeOnly?>("CloseTime")
                        .HasColumnType("time without time zone");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("integer");

                    b.Property<TimeOnly?>("OpenTime")
                        .HasColumnType("time without time zone");

                    b.Property<int>("PoiId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PoiId");

                    b.ToTable("WorkingHours");
                });

            modelBuilder.Entity("GeziRotasi.API.Models.SpecialDayHour", b =>
                {
                    b.HasOne("GeziRotasi.API.Models.Poi", "Poi")
                        .WithMany("SpecialDayHours")
                        .HasForeignKey("PoiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Poi");
                });

            modelBuilder.Entity("GeziRotasi.API.Models.WorkingHour", b =>
                {
                    b.HasOne("GeziRotasi.API.Models.Poi", "Poi")
                        .WithMany("WorkingHours")
                        .HasForeignKey("PoiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Poi");
                });

            modelBuilder.Entity("GeziRotasi.API.Models.Poi", b =>
                {
                    b.Navigation("SpecialDayHours");

                    b.Navigation("WorkingHours");
                });
#pragma warning restore 612, 618
        }
    }
}
