// <auto-generated />
using System;
using GeziRotasi.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GeziRotasi.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8") // Projenizin EF Core versiyonu
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            // --- POI TABLOSUNUN TANIMI ---
            modelBuilder.Entity("GeziRotasi.API.Models.Poi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");
                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Category") // Category artık string olarak saklanıyor
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("ExternalApiId")
                        .HasColumnType("text");

                    b.Property<string>("GirisUcreti")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("OpeningHours")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int?>("OrtalamaZiyaretSuresi")
                        .HasColumnType("integer");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Website")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.ToTable("Pois");

                    // TOHUMLAMA (SEED) VERİSİ
                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Müze",
                            Description = "Osmanlı İmparatorluğu'nun...",
                            Latitude = 41.0116,
                            Longitude = 28.9834,
                            Name = "Topkapı Sarayı"
                        },
                        new
                        {
                            Id = 2,
                            Category = "Alışveriş",
                            Description = "Dünyanın en eski ve en büyük...",
                            Latitude = 41.0107,
                            Longitude = 28.9681,
                            Name = "Kapalıçarşı"
                        },
                        new
                        {
                            Id = 3,
                            Category = "TarihiYapı", // Enum'a uygun olarak düzeltildi
                            Description = "Mavi Camii olarak da bilinir...",
                            Latitude = 41.0054,
                            Longitude = 28.9768,
                            Name = "Sultanahmet Camii"
                        },
                        new
                        {
                            Id = 4,
                            Category = "Müze",
                            Description = "Tarihi yarımadanın kalbinde...",
                            Latitude = 41.0086,
                            Longitude = 28.98,
                            Name = "Ayasofya Tarih ve Deneyim Müzesi"
                        },
                        new
                        {
                            Id = 5,
                            Category = "Müze",
                            Description = "Büyüleyici atmosferi ile...",
                            Latitude = 41.0084,
                            Longitude = 28.9779,
                            Name = "Yerebatan Sarnıcı"
                        });
                });

            // --- DİĞER TABLOLARIN TANIMLARI ---

            modelBuilder.Entity("GeziRotasi.API.Models.Review", b => { /* ... Reviews tablosu tanımı ... */ });
            modelBuilder.Entity("GeziRotasi.API.Models.RouteFeedback", b => { /* ... RouteFeedbacks tablosu tanımı ... */ });

            modelBuilder.Entity("GeziRotasi.API.Models.SpecialDayHour", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("integer");
                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));
                    b.Property<TimeOnly?>("CloseTime").HasColumnType("time without time zone");
                    b.Property<DateOnly>("Date").HasColumnType("date");
                    b.Property<string>("Description").HasMaxLength(100).HasColumnType("character varying(100)");
                    b.Property<TimeOnly?>("OpenTime").HasColumnType("time without time zone");
                    b.Property<int>("PoiId").HasColumnType("integer");
                    b.HasKey("Id");
                    b.HasIndex("PoiId");
                    b.ToTable("SpecialDayHours");
                });

            modelBuilder.Entity("GeziRotasi.API.Models.WorkingHour", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("integer");
                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));
                    b.Property<TimeOnly?>("CloseTime").HasColumnType("time without time zone");
                    b.Property<int>("DayOfWeek").HasColumnType("integer");
                    b.Property<TimeOnly?>("OpenTime").HasColumnType("time without time zone");
                    b.Property<int>("PoiId").HasColumnType("integer");
                    b.HasKey("Id");
                    b.HasIndex("PoiId");
                    b.ToTable("WorkingHours");
                });

            // --- İLİŞKİLERİN TANIMLARI ---

            modelBuilder.Entity("GeziRotasi.API.Models.SpecialDayHour", b =>
                {
                    b.HasOne("GeziRotasi.API.Models.Poi", "Poi")
                        .WithMany("SpecialDayHours")
                        .HasForeignKey("PoiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                    b.Navigation("Poi");
                });

            modelBuilder.Entity("GeziRotasi.API.Models.WorkingHour", b =>
                {
                    b.HasOne("GeziRotasi.API.Models.Poi", "Poi")
                        .WithMany("WorkingHours")
                        .HasForeignKey("PoiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                    b.Navigation("Poi");
                });
            
            modelBuilder.Entity("GeziRotasi.API.Models.Review", b => { /* ... Review ilişkileri ... */ });
            modelBuilder.Entity("GeziRotasi.API.Models.RouteFeedback", b => { /* ... RouteFeedback ilişkileri ... */ });

            modelBuilder.Entity("GeziRotasi.API.Models.Poi", b =>
                {
                    b.Navigation("SpecialDayHours");
                    b.Navigation("WorkingHours");
                    b.Navigation("Reviews"); // Review ilişkisi
                });
#pragma warning restore 612, 618
        }
    }
}
