version: "3.9"

services:
  osrm-driving:
    image: osrm/osrm-backend:latest
    command: osrm-routed --algorithm mld /data/osrm/region.osrm
    ports:
      - "5000:5000"
    volumes:
      - ../osrm-data/driving:/data/osrm:rw
    restart: unless-stopped 

  osrm-foot:
      image: osrm/osrm-backend:latest
      command: osrm-routed --algorithm mld /data/osrm/region.osrm
      ports: ["5002:5000"]
      volumes:
        - ../osrm-data/foot:/data/osrm:rw
      restart: unless-stopped


  osrm-gateway:
    image: nginx:alpine
    ports:
      - "8081:80"   
    volumes:
      - ./nginx/osrm.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - osrm-driving      
      - osrm-foot
    restart: unless-stopped